#!/usr/bin/env python3
"""Generate test/reference.json (schema: test/SCHEMA.md) and test/smoke_expected.h.

Run with the reference repo's interpreter (it has pyswisseph):

    ~/projects/panchangam_mcp/.venv/bin/python test/gen_reference.py

The reference package location is $PANCHANGAM_SRC, default
~/projects/panchangam_mcp/src.
"""
from __future__ import annotations

import json
import os
import random
import subprocess
import sys
from datetime import date, datetime, timedelta
from pathlib import Path
from zoneinfo import ZoneInfo

SRC = Path(os.environ.get("PANCHANGAM_SRC", "~/projects/panchangam_mcp/src")).expanduser()
sys.path.insert(0, str(SRC))

import swisseph as swe  # noqa: E402
from panchangam import angas, ephemeris, muhurta  # noqa: E402
from panchangam.types import Place  # noqa: E402

# Force Moshier regardless of what the reference package defaults to.
ephemeris._EPHE_FLAG = swe.FLG_MOSEPH
ephemeris._SIDEREAL_FLAG = swe.FLG_MOSEPH | swe.FLG_SIDEREAL | swe.FLG_SPEED
ephemeris.configure(ephemeris.Ayanamsa.LAHIRI)

HERE = Path(__file__).resolve().parent
PLACE = Place("Petaling Jaya", 3.1073, 101.6067, "Asia/Kuala_Lumpur", 0.0)
CAP = {"tithi": 4, "nakshatra": 4, "yoga": 4, "karana": 8}  # core/panchangam.h
SEED = 20260919


def jd(when: datetime) -> float:
    return ephemeris._julian_day_ut(when)


def instant(when: datetime) -> dict:
    return {"jd_ut": jd(when), "iso": when.isoformat(timespec="seconds")}


def span(s) -> dict:
    return {"index": s.index, "name": s.name, "start": instant(s.start), "end": instant(s.end)}


def period(p) -> dict:
    return {"start": instant(p.start), "end": instant(p.end)}


def make_case(day: date) -> dict:
    tz = ZoneInfo(PLACE.timezone)
    start = datetime(day.year, day.month, day.day, tzinfo=tz)
    nxt = day + timedelta(days=1)
    nstart = datetime(nxt.year, nxt.month, nxt.day, tzinfo=tz)
    case = {
        "date": day.isoformat(),
        "input": {
            "year": day.year, "month": day.month, "day": day.day,
            "day_start_jd_ut": jd(start), "next_day_start_jd_ut": jd(nstart),
        },
        "sunrise": instant(ephemeris.sunrise(day, PLACE)),
        "sunset": instant(ephemeris.sunset(day, PLACE)),
        "next_sunrise": instant(ephemeris.sunrise(nxt, PLACE)),
    }
    v = angas.vara(day, PLACE)
    case["vara"] = {"index": v.index, "name": v.name,
                    "start": instant(v.start), "end": instant(v.end)}
    for key, fn in (("tithi", angas.tithi), ("nakshatra", angas.nakshatra),
                    ("yoga", angas.yoga), ("karana", angas.karana)):
        spans = fn(day, PLACE)
        assert len(spans) <= CAP[key], (day, key, len(spans))
        case[key] = [span(s) for s in spans]
    case["rahu_kalam"] = period(muhurta.rahu_kalam(day, PLACE))
    case["yamagandam"] = period(muhurta.yamaganda(day, PLACE))
    case["gulika"] = period(muhurta.gulika(day, PLACE))
    return case


def pick_dates() -> list[date]:
    d, end = date(2026, 1, 1), date(2027, 12, 31)
    dates = {d + timedelta(days=i) for i in range((end - d).days + 1)}
    rng = random.Random(SEED)
    lo, hi = date(1950, 1, 1).toordinal(), date(2050, 12, 31).toordinal()
    extra: set[date] = set()
    while len(extra) < 20:
        c = date.fromordinal(rng.randint(lo, hi))
        if c not in dates:
            extra.add(c)
    return sorted(dates | extra)


def git_sha() -> str:
    try:
        out = subprocess.run(["git", "-C", str(SRC), "rev-parse", "--short", "HEAD"],
                             capture_output=True, text=True, check=True)
        return out.stdout.strip()
    except Exception:
        return "unknown"


def write_smoke_expected() -> None:
    """Sidereal (Lahiri, Moshier) Sun/Moon longitudes at 3 JDs for smoke.c."""
    jds = [2451545.0, 2461289.25, 2433282.5]  # 2000-01-01.5, 2026-09-06.75, 1950-01-01
    flags = swe.FLG_MOSEPH | swe.FLG_SIDEREAL
    lines = ["/* Generated by test/gen_reference.py -- do not edit. */",
             "static const struct { double jd, sun, moon; } SMOKE_EXPECTED[] = {"]
    for t in jds:
        sun = swe.calc_ut(t, swe.SUN, flags)[0][0]
        moon = swe.calc_ut(t, swe.MOON, flags)[0][0]
        lines.append(f"    {{ {t!r}, {sun!r}, {moon!r} }},")
    lines.append("};")
    (HERE / "smoke_expected.h").write_text("\n".join(lines) + "\n")


def main() -> None:
    dates = pick_dates()
    doc = {
        "meta": {
            "generator": f"panchangam_mcp @ {git_sha()}",
            "swisseph_version": swe.version,
            "ayanamsa": "lahiri",
            "ephemeris": "moshier",
            "sunrise_definition": "upper_limb_refraction",
            "place": {
                "name": PLACE.name, "latitude_deg": PLACE.latitude,
                "longitude_deg": PLACE.longitude, "elevation_m": PLACE.elevation_m,
                "timezone": PLACE.timezone,
            },
            "tolerance": {"sun_event_seconds": 2.0, "anga_boundary_seconds": 2.0,
                          "muhurta_seconds": 2.0},
            "note": "Local midnights use the zone's historical offsets "
                    "(Asia/Kuala_Lumpur was UTC+7:20..+8 before 1982). "
                    "Random-date seed: %d." % SEED,
        },
        "cases": [make_case(d) for d in dates],
    }
    (HERE / "reference.json").write_text(json.dumps(doc, indent=1) + "\n")
    write_smoke_expected()
    print(f"wrote {len(dates)} cases")


if __name__ == "__main__":
    main()
