/* Generated by test/gen_reference.py -- do not edit. */
static const struct { double jd, sun, moon; } SMOKE_EXPECTED[] = {
    { 2451545.0, 256.51569718931427, 199.47055295238047 },
    { 2461289.25, 138.96097199752032, 67.84743855297788 },
    { 2433282.5, 256.8470501713069, 38.257522187213496 },
};
