/* Smoke test: Swiss Ephemeris (Moshier, sidereal Lahiri) vs the Python values
 * in smoke_expected.h, generated by gen_reference.py. */
#include <math.h>
#include <stdio.h>
#include "swephexp.h"
#include "smoke_expected.h"

#define TOL_DEG 0.001

/* Smallest angular difference, degrees. */
static double angdiff(double a, double b)
{
    double d = fmod(a - b, 360.0);
    if (d > 180.0) d -= 360.0;
    if (d < -180.0) d += 360.0;
    return fabs(d);
}

int main(void)
{
    const int32 flags = SEFLG_MOSEPH | SEFLG_SIDEREAL;
    const int n = (int)(sizeof SMOKE_EXPECTED / sizeof SMOKE_EXPECTED[0]);
    int failures = 0;
    char serr[AS_MAXCH];

    swe_set_sid_mode(SE_SIDM_LAHIRI, 0.0, 0.0);

    for (int i = 0; i < n; i++) {
        const int bodies[2] = { SE_SUN, SE_MOON };
        const double want[2] = { SMOKE_EXPECTED[i].sun, SMOKE_EXPECTED[i].moon };
        const char *names[2] = { "Sun", "Moon" };
        for (int b = 0; b < 2; b++) {
            double xx[6];
            serr[0] = '\0';
            if (swe_calc_ut(SMOKE_EXPECTED[i].jd, bodies[b], flags, xx, serr) < 0) {
                printf("FAIL jd=%.2f %s: swe_calc_ut error: %s\n",
                       SMOKE_EXPECTED[i].jd, names[b], serr);
                failures++;
                continue;
            }
            double d = angdiff(xx[0], want[b]);
            int ok = d <= TOL_DEG;
            printf("%s jd=%.2f %-4s C=%.9f py=%.9f diff=%.2e deg\n",
                   ok ? "ok  " : "FAIL", SMOKE_EXPECTED[i].jd, names[b],
                   xx[0], want[b], d);
            if (!ok) failures++;
        }
    }
    swe_close();
    if (failures) { printf("%d failure(s)\n", failures); return 1; }
    printf("smoke passed (%d dates, tol %.3f deg)\n", n, TOL_DEG);
    return 0;
}
