/* names.h -- GENERATED by tools/gen_names.py. Do not edit; regenerate. */
/* All strings are UTF-8 (currently ASCII transliteration). */
#ifndef PANCHANGAM_NAMES_H
#define PANCHANGAM_NAMES_H

/* Tithi 1..30 -> [index-1]; 1 Shukla Pratipada, 15 Purnima, 30 Amavasya */
static const char *const PANCH_TITHI_NAMES[30] = {
    "Shukla Pratipada",
    "Shukla Dwitiya",
    "Shukla Tritiya",
    "Shukla Chaturthi",
    "Shukla Panchami",
    "Shukla Shashthi",
    "Shukla Saptami",
    "Shukla Ashtami",
    "Shukla Navami",
    "Shukla Dashami",
    "Shukla Ekadashi",
    "Shukla Dwadashi",
    "Shukla Trayodashi",
    "Shukla Chaturdashi",
    "Purnima",
    "Krishna Pratipada",
    "Krishna Dwitiya",
    "Krishna Tritiya",
    "Krishna Chaturthi",
    "Krishna Panchami",
    "Krishna Shashthi",
    "Krishna Saptami",
    "Krishna Ashtami",
    "Krishna Navami",
    "Krishna Dashami",
    "Krishna Ekadashi",
    "Krishna Dwadashi",
    "Krishna Trayodashi",
    "Krishna Chaturdashi",
    "Amavasya",
};

/* Nakshatra 1..27 -> [index-1] */
static const char *const PANCH_NAKSHATRA_NAMES[27] = {
    "Ashwini",
    "Bharani",
    "Krittika",
    "Rohini",
    "Mrigashira",
    "Ardra",
    "Punarvasu",
    "Pushya",
    "Ashlesha",
    "Magha",
    "Purva Phalguni",
    "Uttara Phalguni",
    "Hasta",
    "Chitra",
    "Swati",
    "Vishakha",
    "Anuradha",
    "Jyeshtha",
    "Mula",
    "Purva Ashadha",
    "Uttara Ashadha",
    "Shravana",
    "Dhanishta",
    "Shatabhisha",
    "Purva Bhadrapada",
    "Uttara Bhadrapada",
    "Revati",
};

/* Yoga 1..27 -> [index-1] */
static const char *const PANCH_YOGA_NAMES[27] = {
    "Vishkambha",
    "Priti",
    "Ayushman",
    "Saubhagya",
    "Shobhana",
    "Atiganda",
    "Sukarma",
    "Dhriti",
    "Shula",
    "Ganda",
    "Vriddhi",
    "Dhruva",
    "Vyaghata",
    "Harshana",
    "Vajra",
    "Siddhi",
    "Vyatipata",
    "Variyana",
    "Parigha",
    "Shiva",
    "Siddha",
    "Sadhya",
    "Shubha",
    "Shukla",
    "Brahma",
    "Indra",
    "Vaidhriti",
};

/* Vara 1..7 -> [index-1], Ravivara (Sunday) first */
static const char *const PANCH_VARA_NAMES[7] = {
    "Ravivara",
    "Somavara",
    "Mangalavara",
    "Budhavara",
    "Guruvara",
    "Shukravara",
    "Shanivara",
};

/* Movable karanas; half-tithi index k (0..59) uses [(k-1) % 7] */
static const char *const PANCH_KARANA_MOVABLE[7] = {
    "Bava",
    "Balava",
    "Kaulava",
    "Taitila",
    "Gara",
    "Vanija",
    "Vishti",
};

/* Fixed karanas for k = 0, 57, 58, 59 in that order */
static const char *const PANCH_KARANA_FIXED[4] = {
    "Kimstughna",
    "Shakuni",
    "Chatushpada",
    "Naga",
};

/* Tamil months, Chithirai first. Names only: nothing computes the month yet */
static const char *const PANCH_TAMIL_MONTH_NAMES[12] = {
    "Chithirai",
    "Vaikasi",
    "Aani",
    "Aadi",
    "Aavani",
    "Purattasi",
    "Aippasi",
    "Karthigai",
    "Margazhi",
    "Thai",
    "Maasi",
    "Panguni",
};

#endif /* PANCHANGAM_NAMES_H */
