#!/usr/bin/env python3
"""Reference (Python) formatter for the Slack and X texts, and the fixture for
test/format_test.c.

    python3 tools/gen_format_cases.py

Reads test/reference.json, picks 30 dates (every 25th case), formats each with
the Python implementation below, and writes test/format_cases.txt: the day data
in a line format the C test can parse, plus the expected Slack and X texts.
Names come from the reference file (i.e. straight from the Python panchangam),
so the C side's generated names.h is checked against them.

This file is the specification of the text layout; core/format.c must match it
byte for byte.
"""
from __future__ import annotations

import json
import math
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
UNIX_EPOCH_JD = 2440587.5
UTC_OFFSET = 28800          # MYT
X_MAX_WEIGHT = 280
STEP = 25                   # 750 cases -> 30


def hhmm(jd: float) -> str:
    secs = math.floor((jd - UNIX_EPOCH_JD) * 86400.0 + 0.5)
    sod = (secs + UTC_OFFSET) % 86400
    return f"{sod // 3600:02d}:{(sod % 3600) // 60:02d}"


def x_weight(text: str) -> int:
    """twitter-text weighting: ranges below weigh 1, everything else 2."""
    w = 0
    for ch in text:
        cp = ord(ch)
        if cp <= 4351 or 8192 <= cp <= 8205 or 8208 <= cp <= 8223 or 8242 <= cp <= 8247:
            w += 1
        else:
            w += 2
    return w


def spans_line(label: str, spans: list) -> str:
    body = ", ".join(f"{s['name']} {hhmm(s['start']['jd_ut'])}-{hhmm(s['end']['jd_ut'])}" for s in spans)
    return f"{label}: {body}"


def period_line(label: str, p: dict) -> str:
    return f"{label} {hhmm(p['start']['jd_ut'])}-{hhmm(p['end']['jd_ut'])}"


def tz_label() -> str:
    a = abs(UTC_OFFSET)
    sign = "-" if UTC_OFFSET < 0 else "+"
    if a % 3600 == 0:
        return f"UTC{sign}{a // 3600}"
    return f"UTC{sign}{a // 3600}:{(a % 3600) // 60:02d}"


def format_slack(c: dict) -> str:
    i = c["input"]
    lines = [
        f"*Panchangam {c['date']}* ({c['vara']['name']}, {tz_label()})",
        f"Sunrise {hhmm(c['sunrise']['jd_ut'])}  Sunset {hhmm(c['sunset']['jd_ut'])}",
        spans_line("Tithi", c["tithi"]),
        spans_line("Nakshatra", c["nakshatra"]),
        spans_line("Yoga", c["yoga"]),
        spans_line("Karana", c["karana"]),
        period_line("Rahu Kalam", c["rahu_kalam"]),
        period_line("Yamagandam", c["yamagandam"]),
        period_line("Gulika", c["gulika"]),
    ]
    assert f"{i['year']:04d}-{i['month']:02d}-{i['day']:02d}" == c["date"]
    return "\n".join(lines) + "\n"


def format_x(c: dict) -> tuple[str, str]:
    """(text, dropped) where dropped is '', 'karana' or 'karana+yoga'."""
    for with_yoga, with_karana, dropped in ((True, True, ""), (True, False, "karana"),
                                            (False, False, "karana+yoga")):
        lines = [
            f"\U0001F319 Panchangam {c['date']}, {c['vara']['name']}",
            f"Sunrise {hhmm(c['sunrise']['jd_ut'])} Sunset {hhmm(c['sunset']['jd_ut'])}",
            spans_line("Tithi", c["tithi"]),
            spans_line("Nakshatra", c["nakshatra"]),
        ]
        if with_yoga:
            lines.append(spans_line("Yoga", c["yoga"]))
        if with_karana:
            lines.append(spans_line("Karana", c["karana"]))
        text = "\n".join(lines)
        if x_weight(text) <= X_MAX_WEIGHT:
            return text, dropped
    raise SystemExit(f"{c['date']}: X text still too long after dropping karana and yoga")


def span_rows(tag: str, spans: list) -> list[str]:
    return [f"{tag} {s['index']} {s['start']['jd_ut']!r} {s['end']['jd_ut']!r}" for s in spans]


def main() -> None:
    doc = json.loads((ROOT / "test" / "reference.json").read_text())
    cases = doc["cases"][::STEP]
    assert len(cases) == 30, len(cases)
    out = [f"# Generated by tools/gen_format_cases.py from test/reference.json. UTC offset {UTC_OFFSET}."]
    stats = {"": 0, "karana": 0, "karana+yoga": 0}
    for c in cases:
        i = c["input"]
        x_text, dropped = format_x(c)
        stats[dropped] += 1
        out.append(f"CASE {c['date']}")
        out.append(f"D {i['year']} {i['month']} {i['day']}")
        out.append(f"J {c['sunrise']['jd_ut']!r} {c['sunset']['jd_ut']!r} {c['next_sunrise']['jd_ut']!r}")
        out.append(f"V {c['vara']['index']}")
        for tag, key in (("T", "tithi"), ("N", "nakshatra"), ("Y", "yoga"), ("K", "karana")):
            out.extend(span_rows(tag, c[key]))
        for tag, key in (("R", "rahu_kalam"), ("M", "yamagandam"), ("G", "gulika")):
            p = c[key]
            out.append(f"{tag} {p['start']['jd_ut']!r} {p['end']['jd_ut']!r}")
        out.append("@@SLACK")
        out.append(format_slack(c).rstrip("\n"))
        out.append("@@X")
        out.append(x_text)
        out.append("@@END")
    (ROOT / "test" / "format_cases.txt").write_text("\n".join(out) + "\n", encoding="utf-8")
    print(f"wrote {len(cases)} cases; X drops: {stats}")


if __name__ == "__main__":
    main()
