#!/usr/bin/env python3
"""Generate core/names.h from the Python panchangam name tables.

    ~/projects/panchangam_mcp/.venv/bin/python tools/gen_names.py

Never hand-edit core/names.h; change this script and regenerate. The Python
package location is $PANCHANGAM_SRC (default ~/projects/panchangam_mcp/src).

The Python package has no Tamil month table (and no month calculation), so the
12 Tamil month names below are defined here, not read from Python.
"""
from __future__ import annotations

import os
import sys
from pathlib import Path

SRC = Path(os.environ.get("PANCHANGAM_SRC", "~/projects/panchangam_mcp/src")).expanduser()
sys.path.insert(0, str(SRC))

from panchangam import angas  # noqa: E402

OUT = Path(__file__).resolve().parent.parent / "core" / "names.h"

# Not in the Python package; Latin transliteration, Chithirai (Mesha) first.
TAMIL_MONTHS = (
    "Chithirai", "Vaikasi", "Aani", "Aadi", "Aavani", "Purattasi",
    "Aippasi", "Karthigai", "Margazhi", "Thai", "Maasi", "Panguni",
)


def c_str(s: str) -> str:
    s.encode("utf-8")  # names.h is UTF-8; fail loudly on anything unencodable
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def table(name: str, values, comment: str) -> str:
    body = "\n".join(f"    {c_str(v)}," for v in values)
    return f"/* {comment} */\nstatic const char *const {name}[{len(values)}] = {{\n{body}\n}};\n"


def main() -> None:
    tithi = [angas._tithi_name(n) for n in range(1, 31)]
    nakshatra = list(angas._NAKSHATRA_NAMES)
    yoga = list(angas._YOGA_NAMES)
    vara = list(angas._VARA_NAMES)
    movable = list(angas._KARANA_MOVABLE)
    fixed = angas._KARANA_FIXED  # {1: Kimstughna, 58: Shakuni, 59: Chatushpada, 60: Naga}

    assert (len(tithi), len(nakshatra), len(yoga), len(vara), len(movable)) == (30, 27, 27, 7, 7)

    # Half-tithi index k = 0..59 (C API karana index - 1).
    #   0 Kimstughna, 57 Shakuni, 58 Chatushpada, 59 Naga, else movable[(k-1) % 7]
    fixed_by_k = {0: fixed[1], 57: fixed[58], 58: fixed[59], 59: fixed[60]}
    for k in range(60):
        want = angas._karana_name(k + 1)
        got = fixed_by_k.get(k, movable[(k - 1) % 7])
        assert got == want, (k, got, want)

    parts = [
        "/* names.h -- GENERATED by tools/gen_names.py. Do not edit; regenerate. */\n"
        "/* All strings are UTF-8 (currently ASCII transliteration). */\n"
        "#ifndef PANCHANGAM_NAMES_H\n#define PANCHANGAM_NAMES_H\n",
        table("PANCH_TITHI_NAMES", tithi,
              "Tithi 1..30 -> [index-1]; 1 Shukla Pratipada, 15 Purnima, 30 Amavasya"),
        table("PANCH_NAKSHATRA_NAMES", nakshatra, "Nakshatra 1..27 -> [index-1]"),
        table("PANCH_YOGA_NAMES", yoga, "Yoga 1..27 -> [index-1]"),
        table("PANCH_VARA_NAMES", vara, "Vara 1..7 -> [index-1], Ravivara (Sunday) first"),
        table("PANCH_KARANA_MOVABLE", movable,
              "Movable karanas; half-tithi index k (0..59) uses [(k-1) % 7]"),
        table("PANCH_KARANA_FIXED", [fixed_by_k[0], fixed_by_k[57], fixed_by_k[58], fixed_by_k[59]],
              "Fixed karanas for k = 0, 57, 58, 59 in that order"),
        table("PANCH_TAMIL_MONTH_NAMES", TAMIL_MONTHS,
              "Tamil months, Chithirai first. Names only: nothing computes the month yet"),
        "#endif /* PANCHANGAM_NAMES_H */\n",
    ]
    OUT.write_text("\n".join(parts), encoding="utf-8")
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
